server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AbandonedScope/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  lifecycle:
    timeout-per-shutdown-phase: 15s
management:
  endpoints:
    web:
      exposure:
        exclude: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always